### ISSUE TITLE
Could you add Korean? ko_KR.

### ISSUE THREAD

**Issue by candicom** [softwarerero/meteor-accounts-t9n#107]
Standard language code format may be ko-KR.

But in meteor-accounts-t9n, using es_ES or zh_cn like format.

This is not an issue. The issue is that I want to add Korean language.

Because of not being ko_KR... I can not use Korean in useraccounts package.

Could you add korean? if I send you a translated file?

Do you need ko_KR.less file?

**Comment by softwarerero** [comment]
I think you should be able to use it with useraccounts. @splendido, who wrote useraccounts uses this package as a basis afaik, he also contributed a lot to it. Of course if you privide a translation we will be happy to add it.

**Comment by juliankim** [comment]
I'm willing to provide a translation. Just tell me how :D

**Comment by softwarerero** [comment]
If you are unsure about how to do it you can just pick any of the translations existing in the t9n folder, e.g. en.coffee, translate all strings and send us the result, we will do the rest.

**Comment by juliankim** [comment]
Here we go :D

  add: "추가"
  and: "그리고"
  back: "뒤로"
  changePassword: "비밀번호 변경"
  choosePassword: "비밀번호 선택"
  clickAgree: "클릭함으로써 위 약관을 동의합니다"
  configure: "설정"
  createAccount: "계정 생성"
  currentPassword: "현재 비밀번호"
  dontHaveAnAccount: "계정이 없으세요?"
  email: "이메일"
  emailAddress: "이메일 주소"
  emailResetLink: "이메일 리셋 링크"
  forgotPassword: "비밀번호를 잊으셨나요?"
  ifYouAlreadyHaveAnAccount: "이미 계정이 있으시면"
  newPassword: "새 비밀번호"
  newPasswordAgain: "새 비밀번호(확인)"
  optional: "선택"
  OR: "혹은"
  password: "비밀번호"
  passwordAgain: "비밀번호 (확인)"
  privacyPolicy: "개인정보보호정책"
  remove: "삭제"
  resetYourPassword: "비밀번호 초기화"
  setPassword: "비밀번호 선택"
  sign: "로그인"
  signIn: "로그인"
  signin: "로그인"
  signOut: "로그아웃"
  signUp: "회원가입"
  signupCode: "회원가입 코드"
  signUpWithYourEmailAddress: "이메일로 가입하기"
  terms: "약관"
  updateYourPassword: "비밀번호 업데이트"
  username: "아이디"
  usernameOrEmail: "아이디 혹은 이메일"
  with: "와"


  info:
    emailSent: "이메일 발송"
    emailVerified: "이메일 인증성공"
    passwordChanged: "비밀번호 변경됨"
    passwordReset: "비밀번호 리셋"


  error:
    emailRequired: "이메일이 필요합니다."
    minChar: "비밀번호는 최소 7자 이상입니다."
    pwdsDontMatch: "비밀번호가 맞지않습니다"
    pwOneDigit: "비밀번호에 숫자 하나이상이 필요합니다."
    pwOneLetter: "비밀번호에 문자 하나이상이 필요합니다."
    signInRequired: "로그인이 필요한 서비스입니다."
    signupCodeIncorrect: "가입 코드가 맞지않습니다."
    signupCodeRequired: "가입 코드가 필요합니다."
    usernameIsEmail: "아이디와 이메일은 달라야합니다."
    usernameRequired: "아이디가 필요합니다."


    accounts:

      #---- accounts-base
      #"@" + domain + " email required"
      #"A login handler should return a result or undefined"
      "Email already exists.": "중복된 이메일입니다."
      "Email doesn't match the criteria.": "이메일이 요구조건에 맞지않습니다."
      "Invalid login token": "잘못된 로그인 토큰"
      "Login forbidden": "Login forbidden"
      #"Service " + options.service + " already configured"
      "Service unknown": "Service unknown"
      "Unrecognized options for login request": "Unrecognized options for login request"
      "User validation failed": "인증 실패"
      "Username already exists.": "중복된 아이디입니다."
      "You are not logged in.": "로그인 상태가 아닙니다."
      "You've been logged out by the server. Please log in again.": "서버에 의해 로그아웃되셨습니다 다시 로그인해주세요."
      "Your session has expired. Please log in again.": "세션이 만료되었습니다 다시 로그인해주세요."


      #---- accounts-oauth
      "No matching login attempt found": "No matching login attempt found"


      #---- accounts-password-client
      "Password is old. Please reset your password.": "오래된 비밀번호 입니다 변경해주세요."


      #---- accounts-password
      "Incorrect password": "잘못된 비밀번호 입니다"
      "Invalid email": "잘못된 이메일 입니다"
      "Must be logged in": "로그인이 필요합니다"
      "Need to set a username or email": "아이디나 이메일을 입력해주세요"
      "old password format": "old password format"
      "Password may not be empty": "비밀번호를 입력해주세요"
      "Signups forbidden": "가입이 거부되었습니다"
      "Token expired": "Token expired"
      "Token has invalid email address": "Token has invalid email address"
      "User has no password set": "User has no password set"
      "User not found": "사용자를 찾을수 없습니다"
      "Verify email link expired": "확인 코드가 만료됬습니다"
      "Verify email link is for unknown address": "Verify email link is for unknown address"

      #---- match
      "Match failed": "매치되지 않습니다"

      #---- Misc...
      "Unknown error": "Unknown error"

**Comment by softwarerero** [comment]
Thank you, it is addes with the language code 'ko'.

**Comment by juliankim** [comment]
@softwarerero I just checked how the translation turned out today and it seems to me [with: "와"] string doesn't really translate well, can you actually just just leave it as english 'with'?

**Comment by juliankim** [comment]
emailResetLink: "이메일로 비밀번호 재설정 링크 보내기" looks better too.
