### ISSUE TITLE
Set T9N_LANGUAGES in settings.json

### ISSUE THREAD

**Issue by lyckron** [softwarerero/meteor-accounts-t9n#108]
Hey guys,

Is there any way to set the T9N_LANGUAGES env. in settings.json?

I've tried the following in my "settings.dev.json":

```javascript
{
  "T9N_LANGUAGES": "da"
}
```
................................................
```javascript
{
  "public": {
    "T9N_LANGUAGES": "da"
  }
}
```
...............................................
```javascript
{
  "env": {
    "T9N_LANGUAGES": "da"
  }
}
```
................................................

But all languages is still loaded.

Kind regards

**Comment by softwarerero** [comment]
I do not know how you use the JSON file, but I dont think it will work. Any reason you cannot set an environment variable?

**Comment by lyckron** [comment]
I run meteor with "meteor --settings settings.dev.json" to load project specific settings in development, and a settings.prod.json that easily can be transferred to the environment variable in production.

Well, the only reason would be, to avoid frequently changing the environment variable, when developing multiple projects at the same time, where the t9n settings would conflict.

But my question was most out of curiosity, I guess I could use Docker to set environment variables for each project. 

It would be a bit easier if T9N_LANGUAGES could be set in a settings.json though.

**Comment by softwarerero** [comment]
Ok. I close it for now. If you need this feature reopen the issue. Pull request's are always welcome ;)
