### ISSUE TITLE
pt_BR missing

### ISSUE THREAD

**Issue by juliomac** [softwarerero/meteor-accounts-t9n#109]
HI! On your docs page it says Portuguese (Brazilian) is available, but there is no pt_BR when we do: 

    T9n.getLanguages()

on Browser console it shows:

    ["ar", "ca", "cs", "da", "de", "el", "en", "es", "es_ES", "fa", "fr", "he", "hr", "hu", "id", "it", "ja", "kh", "nl", "no_NB", "pl", "pt", "pt_PT", "ro", "ru", "sl", "sv", "tr", "uk", "vi", "zh_cn", "zh_tw"]

Maybe the "pt" translation itself is good for Brazilian Portuguese already. But for the sake of using the same conventions we get from browser, it would be nice either to change "pt" to "pt-BR" or add a new one.

In fact, I wonder if the other languages like pt_PT, zh_cn and zh_tw would not benefit with the change to pt-PT, zh-cn and zh-tw respectively.

If needed, I could help with the pt_BR translation / check for the project.

What do you think?

**Comment by softwarerero** [comment]
pt was the first Portuguese translation and as far as I understand it is Brazilian Portuguese (please check this if you speak the language) then Portuguese Portuguese was added with pt_PT. You are right about the standard but it would be difficult to change it know because it would probably break al lot of existing code. We could introduce a fallback from "pt_NOTEXISTANT" to "pt" so you would be able to use "pt_BR". Would that work for you?

**Comment by juliomac** [comment]
Yes, but partially. I would still have to convert from "pt-BR" browser output to T9n "pt_BR" standard. Would not change much from what I am doing today. 

It would really help if we have a fallback to "pt-BR" instead which is how browsers are using (Dash instead of underscore). In fact, this could be the solution for the other language with underscore as well. What if  ``` pt_PT, zh_cn and zh_tw ```would fallback to ```pt-PT, zh-CN and zh-TW ``` ?

I also got some doubts and suggestions with the "pt" translation. At Sign-up, I still get untranslated sentences as below. It is strange as the source code show them properly translated already. However, somehow, it is not how it is showing up on browser:

![captura de tela 2015-07-12 17 12 37](https://cloud.githubusercontent.com/assets/3759295/8639751/40518d22-28b9-11e5-8da2-ec97769fee2d.png)

I would also recommend the following changes to pt in order to become more of a pt-BR version. Nothing wrong, just using more commonly written/heard expressions in Brazilian version of Portuguese:

clickAgree: "Ao clicar em Concordar você estará reconhecendo que aceita nossos Termos de Uso"
signUp: “Criar Conta“
signUpWithYourEmailAddress: “Criar conta utilizando seu endereço de e-mail"
"Login forbidden": "Login não permitido”

Regards,

Julio

**Comment by softwarerero** [comment]
The pt_PT to pt-PT could be additional if that really helps. As said for backwards compatibilty reasons it is hard to change file names.

Which package/implementation for log-in is your screen shot based on?

I do not speak Portuguese (but I want to learn it), so I do not want to interfere with the translation. You are invited to send a pull request.

**Comment by juliomac** [comment]
I am trying to use meteor accounts (https://github.com/meteor-useraccounts), still learning.

Sure this fallback to pt-BR would help with coding. Thanks!

I will make the pull request.
