### ISSUE TITLE
Would like to add zh_hk

### ISSUE THREAD

**Issue by daveeel** [softwarerero/meteor-accounts-t9n#110]
I know there's zh_tw and would like to help add zh_hk.
There are quite some different word usages between the two regions.

I checked zh_tw, there are missing translations for phrases like "Verification email lost?", "Send again" etc...
Is there a standard way to get the most recent and complete code list to be translated?
Any guides to start with?

Thanks.

**Comment by softwarerero** [comment]
The easiest way is to grap an existing translation and base your work on that, also have a look at #105. There is always a chance that one of accounts-base, accounts-passwords, accounts-entry or accounts-templates-core changes keys, so if you look for 100% you could check them too.

**Comment by daveeel** [comment]
Thanks for answering. Shall see what I could figure out.
