### ISSUE TITLE
Feature request: Informal version of the German language texts

### ISSUE THREAD

**Issue by derwaldgeist** [softwarerero/meteor-accounts-t9n#117]
At the moment, the German language texts are using the formal "Sie" to address the user. For my application, the informal "Du" would be much better. I could provide the informal version, but I don't know if there is a way to include it in the standard of accounts-t9n?

**Comment by softwarerero** [comment]
If this is needed by more users we should think about introducing language variants. For the moment I would suggest a quick fix. You could overwrite the 7 occurences of 'Sie' on application startup, here is an example in CoffeeScript:

```
very_informal_de =
  clickAgree: 'Wenn Du Dich hier echt anmeldest akzeptierst Du auf Gedeih und Verderb unsere'
  error:
    signInRequired: 'Du musst Dich einloggen, Alter.'
T9n.map 'de', very_informal_de
```

**Comment by derwaldgeist** [comment]
:+1:

**Comment by softwarerero** [comment]
With version 1.2.0 you can now do this:
```
very_informal_de =
  clickAgree: 'Wenn Du Dich hier echt anmeldest akzeptierst Du auf Gedeih und Verderb unsere'
  error:
    signInRequired: 'Du musst Dich einloggen, Alter.'
T9n.map 'de_DE_dorfslang', very_informal_de
```
This would look for translations in 'de_DE_dorfslang', then in 'de_DE' and finally in 'de'.

**Comment by derwaldgeist** [comment]
Thanks!
