### ISSUE TITLE
process.env.T9N_LANGUAGES not working

### ISSUE THREAD

**Issue by thomasspiesser** [softwarerero/meteor-accounts-t9n#119]
Hey there,
I'm trying to not send all languages to the client like this

    env T9N_LANGUAGES="de,en" meteor

shell is fish not bash, hence the `env` in front. this gives me

    > process.env.T9N_LANGUAGES
    'de,en'

and also the code from you package.js works just fine 

    > if(process.env.T9N_LANGUAGES) {
      LANGUAGES = process.env.T9N_LANGUAGES.split(',');
    } 
    > LANGUAGES
    [ 'de', 'en' ]

still in the browser console I am able see all languages in `T9n.maps`. 

What am I doing wrong?

**Comment by softwarerero** [comment]
I cannot see anything wrong here. What does the FILES array in package.js look like?

**Comment by thomasspiesser** [comment]
how can I check that?

**Comment by softwarerero** [comment]
I thought the same way as you tested LANGUAGES is set to the right value. Now I see that you mentioned the browser console. This should be tested on the server not on the client with a debugger or simply introducing some additional logging.

**Comment by thomasspiesser** [comment]
sorry for the confusion, tested process.env and LANGUAGES using `meteor shell`.

**Comment by thomasspiesser** [comment]
so you suggest to fork, build form local and put logs in?

**Comment by softwarerero** [comment]
Thats the hard way. You can also require it with npm, look where the package is stored under ~/.meteorite and do some quick (and dirty) changes.

**Comment by thomasspiesser** [comment]
ok got it, was really simple
    
    softwarerero:accounts-t9n@1.0.9

it's just not supported in my installed version. I don't know, why it's not the latest version but obviously some package might dep on an older version...

**Comment by nicolaslopezj** [comment]
It isn't working for me. Only works when I download the package manually and put it in the packages folder.

**Comment by softwarerero** [comment]
What exactly is not working?

**Comment by nicolaslopezj** [comment]
Always sends all the languages

**Comment by softwarerero** [comment]
Sorry, I'm not able to reproduce this.

**Comment by thomasspiesser** [comment]
i also never managed to stop sending all languages (despite correct version).

**Comment by nicolaslopezj** [comment]
Make the app use the package from the packages server, you can change the name of the folder or move it.

**Comment by fabyeah** [comment]
I have T9N_LANGUAGES="de,en" and I'm using version 1.1.4 and it's also sending all languages. @thomasspiesser reopen the issue, if it's not working for you?

**Comment by softwarerero** [comment]
I found no clean solution for this but at least a workaround. This is taken from the updated readme: "With the current package manager this does not work anymore. If you need that functionality delete ~/.meteor/packages/softwarerero_accounts-t9n and instead copy it directly into your project (you can go to myproject/packages and issue git clone https://github.com/softwarerero/meteor-accounts-t9n.git). Now it should work again."
