### ISSUE TITLE
Error after updating to Meteor 1.2.0

### ISSUE THREAD

**Issue by francesco-marafini** [softwarerero/meteor-accounts-t9n#122]
UI.registerTemplate is changed to Tracker.registerTemplate

**Comment by mbernath** [comment]
@softwarerero It seems that 1.1.5 is not published yet. Would you mind publishing it? I opened an issue in useraccounts core to upgrade their dependency to accounts-t9n...

**Comment by softwarerero** [comment]
I just published 1.1.6.
