### ISSUE TITLE
Beginner Question

### ISSUE THREAD

**Issue by sangyoo91** [softwarerero/meteor-accounts-t9n#128]
How would I use this to translate accounts-password Meteor.Error messages into some other language than English?

**Comment by sangyoo91** [comment]
Right now I have this.

`/lib/t9n/t9n.coffee`

```
T9n.setLanguage("ko")
```

But my accounts errors are not returning in Korean.

**Comment by softwarerero** [comment]
I wonder how t9n.coffee ended up in a lib folder, that sounds odd. Have you installed with `meteor add softwarerero:accounts-t9n`?

**Comment by sangyoo91** [comment]
Thank you so much for the prompt response. I added it there because I'm clueless on how I can use this package.

**Comment by softwarerero** [comment]
You should delete the file from lib and then from the command line in the top folder of your project use `meteor add` as above. This is the same procedure for any meteor package. Please close this issue if it works.

**Comment by sangyoo91** [comment]
I did add the package. I feel like I just don't understand how to initiate (implement) it after adding the package.

**Comment by softwarerero** [comment]
Set the language like you did (it works on the client and on the server), after that try `T9n.get('yourErrorCode')`, this should give you the Korean translation.

**Comment by sangyoo91** [comment]
`T9n.setLanguage("ko")`

I thought this would automatically change all the errors automatically

**Comment by sangyoo91** [comment]
```
Meteor.loginWithPassword obj.user, obj.password, (err, res) ->
      if err
        console.log T9n.get(err.reason)
```

I have this for my signin, but I'm not getting a korean message.

**Comment by softwarerero** [comment]
Look what text err.reason gives you and then look if a translation is available in https://github.com/softwarerero/meteor-accounts-t9n/blob/master/t9n/ko.coffee. If not you can add it.

**Comment by sangyoo91** [comment]
It is in there. Am I implementing it correctly? Because I think I am and it isn't working.

**Comment by softwarerero** [comment]
I do not see an error in your code.

**Comment by sangyoo91** [comment]
Had to do this to make it work

```
Meteor.loginWithPassword obj.user, obj.password, (err, res) ->
      if err
        console.log T9n.get('error.accounts.' + err.reason)
```
