### ISSUE TITLE
Can't it set language automatically by http request header Accept-Language?

### ISSUE THREAD

**Issue by qwIvan** [softwarerero/meteor-accounts-t9n#132]

**Comment by softwarerero** [comment]
There are different ways to reach that. If you use for example https://atmospherejs.com/gadicohen/headers you can do:
```
Meteor.startup ->
  T9n.setLanguage headers.get('accept-language')
```
But you need to assure that the browser's accept-language exists as a translation with the same name.

**Comment by softwarerero** [comment]
Hello @qwIvan, the issue is still open. Does the solution not work for you?

**Comment by softwarerero** [comment]
From the docu of version 1.2.2 (release 5 minutes ago):
"Starting from (v.1.2.2) you can also do setLanguage('en-GB') and it gets converted internally to 'en_GB'. This is usefull for taking the language string directly from an http header. "
