### ISSUE TITLE
Incorrect German language texts

### ISSUE THREAD

**Issue by derwaldgeist** [softwarerero/meteor-accounts-t9n#136]
While I was implementing an informal "Du" version for the German language texts, I saw that two of the existing "Sie" texts are incorrect:

```
"You've been logged out by the server. Please log in again.": "Der Server hat Dich ausgeloggt. Bitte melde Dich erneut an."
```

This is already using "Du" instead of "Sie", which is inconsistent to the rest of the texts.

```
"A new email has been sent to you. If the email doesn't show up in your inbox, be sure to check your spam folder." : "Eine neue Email wurde an Sie verschickt. Sollte sich die Email nicht in Ihrem Posteingang befinden, prüfen Sie bitten Ihren Spamordner."
```

It has to be "bitte" instead of "bitten" at the end of the last sentence.

I would also prefer the term "abmelden" / "abgemeldet" instead of "ausloggen" / "ausgeloggt". In German, this is considered as "Denglisch", i.e. a mix of German and English.

**Comment by softwarerero** [comment]
Thanks, it's fixed.
