### ISSUE TITLE
Fall back xx_YY to xx if YY not present?

### ISSUE THREAD

**Issue by lfilho** [softwarerero/meteor-accounts-t9n#137]
Hey @softwarerero thanks for you handy package. Appreciate it!

I think it would be a great idea falling back from `xx_YY` to `xx`.

Example: we today have `pt` and `pt_PT` but not `pt_BR`. So it would be nice if after a `T9n.setLanguage('pt_BR')` and not finding it, you would fallback to `pt`.

What do you think? Thanks

**Comment by softwarerero** [comment]
This should work since version 1.2.

**Comment by lfilho** [comment]
Uhm... I will test it again soon, but IIRC I did set it to `pt-BR` and it fell back to english. Then changed to `pt` and it worked.

Will double check and post my findings here. Thanks again

**Comment by softwarerero** [comment]
try pt_BR instead of pt-BR

**Comment by lfilho** [comment]
That's another thing. `pt-BR` is what comes from a http header, for
instance... Shouldn't we support that too?

Em sex, 22 de jan de 2016 às 18:25, Stefan Undorf <notifications@github.com>
escreveu:

**Comment by softwarerero** [comment]
Well now we have two issues into one. From the docu of version 1.2.2 (release 5 minutes ago):
"Starting from (v.1.2.2) you can also do setLanguage('en-GB') and it gets converted internally to 'en_GB'. This is usefull for taking the language string directly from an http header. "

**Comment by softwarerero** [comment]
Does falling back from xx_YY to xx still not work for you? All test's run clean.

**Comment by lfilho** [comment]
So, here's my code snippet:

```javascript
if (Meteor.isClient) {
    Meteor.startup(() => {
        Tracker.autorun(() => {
            const userLanguage = 'pt';
            T9n.setLanguage(userLanguage);
            TAPi18n.setLanguage(userLanguage);
        });
    });
}
```

If I use `const userLanguage = 'pt-BR';` or `const userLanguage = 'pt_BR';`, the app refreshes but login screen is still in English. But if changed it to `const userLanguage = 'pt';`, then it works and login screen is in Portuguese.

What am I missing?
Here are my versions:
- Meteor 1.2.1
- softwarerero:accounts-t9n@1.2.2
- tap:i18n@1.7.0

**Comment by softwarerero** [comment]
What do you mean by login sceen? Does it come from tap:i18n? You example uses just 'pt'. You should really use 'pt_BR' (or similar) like your description says.

**Comment by lfilho** [comment]
By login screen I mean regular meteor accounts ui login screen. tap:i18n
doesn't provide any translation out of the box...

I did try 'pt_BR' (and 'pt-BR'). Please re-read my previous comment. But
'pt' was the only way it worked...

Em dom, 24 de jan de 2016 às 15:13, Stefan Undorf <notifications@github.com>
escreveu:

**Comment by softwarerero** [comment]
I really do not know what to do about this. Everything works when I test it and I do not understand what you are doing exactly. Have you run the test locally (just go to tests/t9nDriver and type `meteor`)? Could you share a gist or something showing the problem?

**Comment by lfilho** [comment]
So, I did a `meteor update` just to confirm I had the lastest version.
Then I did a `rm -rf .meteor/local`.
Then started the app afresh: `meteor`.

I started debugging T9n and here's what I got:

![image](https://cloud.githubusercontent.com/assets/282756/12698947/e29f4fe8-c791-11e5-9fe5-bb53ba58600d.png)

So `pt_BR` is arriving at that point. But there's no `pt_BR` in the `@maps` var:

![image](https://cloud.githubusercontent.com/assets/282756/12698952/1b5fe04a-c792-11e5-8fc2-a35b3a28bd1a.png)

So then I get this error back: `Uncaught TypeError: Cannot convert undefined or null to object`

![image](https://cloud.githubusercontent.com/assets/282756/12698958/3c2379cc-c792-11e5-8db1-52af14734194.png)

I didn't find that test folder you mentioned in your comment. Where is it exactly?

Thanks

**Comment by softwarerero** [comment]
So you trying to setLanguage 'pt_BR' but the translations is not defined. That should throw a better error (I fixed that with bc7a7255e97e6c460e9ca73a882ddc3fc5e1d656). So I guess you want to create a translation pt_BR first.

**Comment by lfilho** [comment]
That's the thing, which is my original claim in this issue: shouldn't we fallback to `pt` if `pt_BR` is not present?
Use case: a user lands in our website and his http headers are set to accept `pt_BR`, right now, t9n won't find `pt_BR` and will serve english to the user. But we have the `pt` language, so it would be best to show fallback to it before defaulting to english, wouldn't it?

I mean, if the user is a portuguese speaker and doesn't know english, I think re rather have a non-localized/generic version of portuguese than have it in english, wouldn't them?

**Comment by lfilho** [comment]
Also, pt-PT and pt_PT are full objects in the @maps var (see screenshot above). Wouldn't it be better not to duplicate that data and just normalize the lookups to be dash-underscore-insensitive?

Thanks

**Comment by softwarerero** [comment]
So finally I understand. You have two feature requests:
1. To be able to set a non existing language variant and instead of throwing an exception silently use a parent language. With your exapmle this sounds reasonable. Maybe we should do this and print only a warning. I'll have a look.
2. Only use one map for language synonyms. From my standpoint that would be nice to have but it's not a big deal. Open a separate issue if it is important to you, also a pull-request would be welcome.

**Comment by softwarerero** [comment]
Your first feature request is here: 9503d551d166c738ee8e324b6d2851015cfd7c43. It's not released yet.

**Comment by lfilho** [comment]
Looking good! Thanks, man!

**Comment by softwarerero** [comment]
I just released version 1.3. Please give it a try.

**Comment by lfilho** [comment]
I'm moving to a new country and new job the next days, I'll give it a go in a few weeks. But feel free to close this one. 

Thanks a lot! If I notice something wrong I'll post again here :)

All the best

**Comment by softwarerero** [comment]
Great. Reopen it if you still find an issue.
