### ISSUE TITLE
Does t9n work well with meteor 1.3?

### ISSUE THREAD

**Issue by ChenLi0830** [softwarerero/meteor-accounts-t9n#142]
Hi there,

I am trying to use t9n with my project. It is developed base on meteor 1.3 beta.8, and I am having trouble make t9n work in it. T9n.setLanguage is placed in the lop-level outside Meteor.startup like this
```
T9n.setLanguage("zh_cn");

Meteor.startup(function () {
...
})
```

Project can run with no problem, however, the error messages from accounts-password package are not translated. For example, when I try to register using an existed email, I still got this message "Email already exists."

I'm wondering if meteor-accounts-t9n works with Meteor 1.3? If so, what might be the reason that caused it not working in my project? 
Thanks.

**Comment by softwarerero** [comment]
Meteor 1.3 is not tested yet and I'm sorry right now I don't know what the problem might be.

**Comment by ChenLi0830** [comment]
@softwarerero  Thanks for your quick reply. I'll give it another try and if I have any luck with it, I'll post the result here.

**Comment by softwarerero** [comment]
Today I tested with 1.3-rc.8, this works without errors. Although I have not looked if something has changed in accounts-password. Maybe you can retest and let me know what results you get.

**Comment by ChenLi0830** [comment]
Hi @softwarerero, thanks for that! I'll give it a try again and let you know how it turns out.

**Comment by tcastelli** [comment]
I'm having the same problem with 1.3.2.4, has anyone found the problem too?

**Comment by ChenLi0830** [comment]
Sorry for the delay. I can confirm it is working fine for Meteor 1.3.2.4. 

I am using it like this to get the error translation. Is it the correct to use it? 
T9n.get('error.accounts.'+error.reason),
