### ISSUE TITLE
Remove dependency on Blaze

### ISSUE THREAD

**Issue by timbrandin** [softwarerero/meteor-accounts-t9n#143]
See this issue, and please remove the dependency you have on Blaze.
https://github.com/studiointeract/accounts-ui/issues/15

**Comment by timbrandin** [comment]
We might need to add a check for existance of Template:
https://github.com/softwarerero/meteor-accounts-t9n/blob/master/t9n.coffee#L3

**Comment by softwarerero** [comment]
should be fixed with 1.3.1

**Comment by timbrandin** [comment]
Awesome thx. Updating `std:accounts-ui`, btw, maybe we can get some more strings in later?

**Comment by timbrandin** [comment]
I have some strings that would be good to get in here, see https://github.com/studiointeract/accounts-ui/tree/master/imports/startup/i18n

**Comment by softwarerero** [comment]
sure, if they are usefull for many users

**Comment by timbrandin** [comment]
great, do you have a strategy to get other languages?

**Comment by softwarerero** [comment]
Everyone scratches his itch, so if enough users need a translation the chances are good that somebody provides it. Sometimes I would like to send an email to all contributers that there are new strings to translate but I see no easy way to do this on GitHub.

**Comment by timbrandin** [comment]
Yeah, that's true. If they need it they'll add it! Great repo! :dancer: Could you publish the two latest PRs?
