### ISSUE TITLE
Installed, but still get "User not found" instead of translation

### ISSUE THREAD

**Issue by ScyDev** [softwarerero/meteor-accounts-t9n#148]
Is calling `T9n.setLanguage("de");` somewhere in client code all that is necessary?

**Comment by softwarerero** [comment]
It should work, can you show your code?

**Comment by ScyDev** [comment]
This is the place where I expected the error message "User not found" from Meteor to be translated:
https://github.com/ScyDev/reaction/blob/development/packages/reaction-accounts/client/templates/signIn/signIn.js#L65

**Comment by softwarerero** [comment]
You need to call `T9n.get('name')` to translate the actual string.

**Comment by ScyDev** [comment]
So... this package doesn't automatically translate all UI output of the meteor standard packages?
I thought that would make sense.

**Comment by softwarerero** [comment]
If you have an idea how that could be posible that would be a great feature.

**Comment by ScyDev** [comment]
I assumed something with hooks :)
But I don't really know the inner workings of the standard packages.
Thanks for the package anyway!
