### ISSUE TITLE
Error: language et does not exist

### ISSUE THREAD

**Issue by krishaamer** [softwarerero/meteor-accounts-t9n#158]
Hello, I'm not directly using your package however I think it's being included by another package in my app and I'm getting the following error:
setLanguage — t9n.coffee:68 Error: language et does not exist

I don't actually need to translate error messages so is there an easy way to switch this off?

Thanks,
Kris

**Comment by softwarerero** [comment]
Simply delete the code that says `setLanguage`. There is no translation `et`.

**Comment by krishaamer** [comment]
It's somewhere inside another package, so I don't have access to it.

**Comment by krishaamer** [comment]
I wasn't abel to solve this, so added a full Estonian translation: https://github.com/softwarerero/meteor-accounts-t9n/pull/159
