### ISSUE TITLE
Translations consume too much bandwidth

### ISSUE THREAD

**Issue by jancurn** [softwarerero/meteor-accounts-t9n#161]
It would be great if the package was fetching the translations from the server on the fly only when they are needed. Currently all the strings are passed to all clients all the time, which consumes a few hundred kilobytes of bandwidth. I can't even use the T9N_LANGUAGES environment variable trick to limit the number of translations loaded by clients, and copying the package directly to our project and modifying it would break the automatic upgrades of the package.

**Comment by softwarerero** [comment]
I agree, pull requests are welcome.

**Comment by softwarerero** [comment]
With release 2.0.0 it is possible to use this package with npm, that way the language files are not loaded eagerly and can be imported as needed.
