### ISSUE TITLE
Update es translations (patch provided)

### ISSUE THREAD

**Issue by in0ni** [softwarerero/meteor-accounts-t9n#167]
Saw there are a few translations missing from es.coffee. Issuing a pull request, would really appreciate if you could update :)

**Comment by softwarerero** [comment]
Is this still an issue?

**Comment by in0ni** [comment]
from what i can tell -- yes. if you apply the patch the spanish translations will be complete ;)

**Comment by softwarerero** [comment]
can you send a pull request please?

**Comment by in0ni** [comment]
#168
