### ISSUE TITLE
bug in fr_CA.coffee prevents meteor 1.5 startup

### ISSUE THREAD

**Issue by BigFatDog** [softwarerero/meteor-accounts-t9n#182]
Hello. My application cannot startup with Meteor 1.5, due to error: "ReferenceError: fr is not defined
W20170704-19:22:12.926(-4)? (STDERR)     at packages/softwarerero_accounts-t9n.js:1907:15'

I locate the fr variable bug in fr_CA.coffee:

```
var fr_CA = {};
T9n.map "fr", fr

```
it should be 
```
var fr_CA = {};
T9n.map "fr_CA", fr_CA

```

**Comment by softwarerero** [comment]
Just pushed 1.3.11 with a hotfix.

**Comment by BigFatDog** [comment]
thank you for your quick support.

**Comment by softwarerero** [comment]
Is this bug still open?

**Comment by softwarerero** [comment]
Closing this as it should be fixed

**Comment by BigFatDog** [comment]
Sorry for late reply. I confirm this has been fixed
