### ISSUE TITLE
Tried everything

### ISSUE THREAD

**Issue by Vandell63** [softwarerero/meteor-accounts-t9n#183]
Hy there,
I tried everything but it is not working,
After install the package I add : T9n.setLanguage('fr') in /imports/startup/both then in /imports/startup/client and ending with /imports/startup/server. 
I try to get all 'fr' config and import manually 
Like this in : 
```
	       'User has no password set': 'L\'utilisateur n\'a pas de mot de passe',
		'User not found': 'Utilisateur inconnu',
		'Verify email link expired': 'Lien de vérification d\'e-mail expiré',
		'Please verify your email first. Check the email and follow the link!': 'Votre email n\'est pas validé. Merci de cliquer sur le lien que vous avez reçu',
		'Verify email link is for unknown address': 'Le lien de vérification d\'e-mail réfère à une adresse inconnue',

		// #---- match
		'Match failed': 'La correspondance a échoué',

		// #---- Misc...
		'Unknown error': 'Erreur inconnue',

	},
};


T9n.map('fr', fr);
T9n.setLanguage('fr');
```

I think that i need a simple example with the Account.createUser for example... or do I miss something.
Thx in advance.

**Comment by softwarerero** [comment]
Hi you could have a look at https://github.com/softwarerero/meteor-accounts-t9n/tree/master/tests/t9nDriver, those are some tests which demonstrate most of the features. If this doesn't help you can you please show a running project example and what error you get or what doesn't work exactly?

**Comment by Vandell63** [comment]
Thx you for your response. I'm sorry but i'm just started with this package so i 've just initialize T9n with the T9n.setLanguage('fr'). Example : 
```Accounts.createUser(options, (err) => {
  if(err){
    Bert.alert(err.reason,'danger');
  }
})```
what will be the right translation : `Bert.alert(T9n.get()....???
I though at the beginning that it was automatic...

**Comment by softwarerero** [comment]
I am not really sure what you are doing. Do you have an example online and can tell exactly what is not working for you?

**Comment by Vandell63** [comment]
Hey, I though that this package make an automatic translation for the Meteor server error like 'User not exist' or 'User already exist'. Because we don't know what message Meteor could send after an error, i though that this package could handle the error type and generate an automatic translation from this error message. My bad, thx for your support @softwarerero .

**Comment by softwarerero** [comment]
Please have a look at the new examples folder with two Meteor projects. One example shows how to work with Atmosphere packages and the how to use t9n with npm/yarn. I hope this helps.

**Comment by Vandell63** [comment]
The best example that you could give is : 
If you know that methods could you give some account Errors so 
```
T9n.setLanguage('de');
Meteor.call('user.insert',data, (err) => { 
 if(err) {
   const error = T9n.get(`error.accounts.${err.reason}`); // Catch the multiple different account error 
   console.log(error) // Give you the right account error in the right translation
  }
})
```
That's all . Something that i don't understand in this package ?
