### ISSUE TITLE
Does it work with npm or not?

### ISSUE THREAD

**Issue by Floriferous** [softwarerero/meteor-accounts-t9n#187]
Can you provide some clarification regarding the npm transition (or not) and eagerly loaded languages?

I saw that in 2.0.0 you introduced an npm package, and then removed examples related to it in 2.0.1?

I tried installing the npm package with `npm install meteor-accounts-t9n`, but the app crashes because it tries to import `meteor/tracker` (which is why you went back?).

Can you make it clear what works and what does not? And specify whether issue #161 is truly solved or not, the README is a bit confusing?

Thanks for your work! :)

**Comment by softwarerero** [comment]
Yes, I ran into the same thing. I need to find some free time to look into and document it well, with a little luck I get to it on the weekend.

**Comment by softwarerero** [comment]
The reason why `examples/meteorNpm` works for me is that I used a symbolic link to `meteor-accounts-t9n` in `node_modules`. When I create a new Meteor and just `npm install meteor-accounts-t9n` I see the same error as you. I would regard this feature as broken for the moment. There is some hope that MDG will release a npm package of Tracker, then this should work as expected.

If you want to use it as an npm package today the workaournd is to clone `meteor-accounts-t9n` to a different directory and put a symbolic link in `node_modules` of your Meteor project.

**Comment by softwarerero** [comment]
From version 2.3.0 on this will work only as a npm package, Meteor/Atmosphere packages are no longer supported.
