### ISSUE TITLE
Meteor 1.6 cannot be used

### ISSUE THREAD

**Issue by eugle** [softwarerero/meteor-accounts-t9n#189]
While checking for softwarerero:accounts-t9n@2.0.3:
error: No compatible binary build found for this package. Contact the
package author and ask them to publish it for your platform.

**Comment by Floriferous** [comment]
This just happened to me as well. installed softwarerero:accounts-t9n@1.3.11 instead.

**Comment by softwarerero** [comment]
I guess the cause is an error I get since a few versions when I do `meteor publish`. The first time it's returning 
```
=> Errors while publishing:

While uploading build:
error: Error: ETIMEDOUT
```
and on a second call: 
```
=> Errors while publishing:

While pre-publishing package softwarerero:accounts-t9n:
error: Version already exists
```
I have not found any explanation for this yet.

**Comment by softwarerero** [comment]
From version 2.3.0 on this should work with Meteor 1.6 as a npm package. Note: Meteor/Atmosphere packages are no longer supported.

**Comment by softwarerero** [comment]
Version 2.3.0 or newer should work with Meteor 1.6. I just tested version 2.4.0 successfully with Meteor 1.8.1.
