### ISSUE TITLE
coffeescript dependency too low now. Update required

### ISSUE THREAD

**Issue by tab00** [softwarerero/meteor-accounts-t9n#190]
Please update coffeescript dependency to the latest version. 

I have been unable to make required updates to some other packages because they require a minimum version of coffeescript that is higher than the maximum allowed by accounts-t9n.

**Comment by pfafman** [comment]
You just need to remove these lines from `package.js`

```
if (api.versionsFrom)
    api.versionsFrom("METEOR@1.1");
```

**Comment by softwarerero** [comment]
Just updated to CoffeeScript 2.1.1, but it's anyway only a dev dependency, so it should be irrelevant for your project.

**Comment by softwarerero** [comment]
I see, in version 2.3.0 the dependency on `CoffeeScript` is completely removed and optional. Please remove the Meteor package from your app and install it as a npm package, this is the only way it's working from now on.

**Comment by tab00** [comment]
Thank you, though there are Meteor packages that depend on the softwarerero:accounts-t9n Meteor package, e.g. [useraccounts:core](https://github.com/meteor-useraccounts/core) that I also use. What should be done about that?

**Comment by softwarerero** [comment]
As useraccounts:core  depends on a fixed version of meteor-accounts-t9n (1.3.3) at least it should not break, of course you still will have the dependency on CoffeeScript. One solution for you could be to fork useraccounts:core and update the dependencies, I see that you opened an issue there, but I'm not sure if useraccounts:core is still maintained.

**Comment by tab00** [comment]
I use peerlibrary:user-extra which requires almost the latest version of coffeescript.

I've cloned useraccounts:core to a local packages directory and added code to use the NPM version of meteor-accounts-t9n:
```
import { T9n } from 'meteor-accounts-t9n'
```

This makes the text on the user account pages, but they appear as camel-case, e.g. "signIn", "forgotPassword". So I assume that default language had not been set. So I tried to add `T9n.setLanguage('en')` but I get the error "language en does not exist"

`T9n.getLanguages()` returns an empty array.

How can this be fixed?

**Comment by softwarerero** [comment]
This is expected, you have to load the translations you use yourself and do some more initialization work than before. Not loading the translations by default is actually a feature many have requested to safe bandwidth. The other steps cannot as easily automated using `npm` as with a Meteor package, so this is basically what you have to do (copied from the readme):   

## Installation and initialisation
`meteor npm install --save meteor-accounts-t9n`

### Require (or import) T9n (this was a global variable in former versions)
`T9n = (require 'meteor-accounts-t9n').T9n`

### Add English default translations (to this for any language you want)
T9n.map 'en', require 'meteor-accounts-t9n/build/en'
`T9n.map 'en', # add another t9n to the English dictionary
  'another cool t9n', 'another cool translation'`

### Register Tracker (optional and client only)
`T9n.setTracker require 'meteor/tracker'`

### Register `t9n` template helper (client only, this was done automatically before)
`Template.registerHelper 't9n', (x, params) -> T9n.get(x, true, params.hash)`

You can find a client side example [here](https://github.com/softwarerero/meteor-accounts-t9n-example/blob/master/client/client.coffee).

**Comment by tab00** [comment]
I just want the built-in English translations in https://github.com/softwarerero/meteor-accounts-t9n/blob/master/t9n/en.coffee.

Isn't this enough?:
```
import { T9n } from 'meteor-accounts-t9n'
T9n.setLanguage('en')
```

**Comment by softwarerero** [comment]
Great that you worked it out. You are right, when I have time I will add another example in plain JavaScript.

**Comment by Adriano72** [comment]
With all respect, but the guide is really poor and the fact that it's in coffeescript is difficult to understand...

**Comment by softwarerero** [comment]
Here is another example how I recently integrated in a Meteor project:

```
import { T9n } from 'meteor-accounts-t9n'
T9n.setTracker(require 'meteor/tracker')

@T9n = T9n

T9n.map 'en',
  Dashboard: 'Dashboard'

T9n.map 'es',
  Dashboard: 'Tablero'

T9n.setLanguage('es_PY')
# console.log T9n.get('Dashboard')
```

To those complaining about the difficulty of CoffeeScript have you thought that the package is written CoffeeScript and that documenting it in CoffeeScript is maybe easier for CoffeeScript developers?
