### ISSUE TITLE
How to reduce size and upload only few languages now?

### ISSUE THREAD

**Issue by juliomac** [softwarerero/meteor-accounts-t9n#192]
I am using this package exclusively because of meteor-useraccounts dependency. I do have few translations between Portuguese, Spanish and English and that's it. But the package is taking a wooping 188Kb amount of load! 20% of my total app...

I am a bit confused about the solution proposed. It involves at the same time installing an npm version and clone a atmosphere package locally? Did I get it right? How would I then take out all other languages?

**Comment by softwarerero** [comment]
You can either use the Atmosphere package or the npm package, it does no make sense to use both at the same time.

The Atmosphere package comes with all the languages included, you have less initialization work at the cost of a bigger bundle size.

If you prefer a smaller bundle I recommend to use the npm version only. You can find an example in this repository how to initialize it and import language files at the client and server: https://github.com/softwarerero/meteor-accounts-t9n-example.

**Comment by juliomac** [comment]
Dear @softwarerero , I finally took the courage to move on to npm package.

I struggle a bit with your CoffeeScript example and I was not competent enough to translate this require ```T9n.map('en', require('meteor-accounts-t9n/build/en'));```  into a valid ```import```statement. But leaving it as require worked well.


The problem is that I am still seeing a hefty 187K softwareerero_accounts-t9n on my bundle visualizer. It seems it have reduced nothing. Is that really that much or I am doing something wrong?

**Comment by juliomac** [comment]
Hummm... I use for T9n because of its useraccounts dependency. I can see it is there in the tree:


      useraccounts:bootstrap@1.14.2                 
    ├── templating@1.3.2 (expanded above)         
    ├── underscore@1.0.10                         
    └─┬ useraccounts:core@1.14.2                  
      ├── accounts-base@1.4.2 (expanded above)    
      ├── blaze@2.3.2 (expanded above)            
     ├── check@1.3.0 (top level)                 
     ├── http@1.4.0 (expanded above)             
      ├── jquuserery@1.11.10 (expanded above)         
      ├── reactive-dict@1.2.0 (expanded above)    
      ├── reactive-var@1.0.11 (top level)         
      ├─┬ softwarerero:accounts-t9n@1.3.11        
      │ ├── coffeescript@1.0.17 (expanded above)  
      │ └── deps@1.0.12 (expanded above)          
      ├── templating@1.3.2 (expanded above)       
      └── underscore@1.0.10    


I don't know how the 'magic' of Meteor works and just thought it would not load a dependency if found one already loaded (even if via npm).

So what would be my options? Fork a local version of the useraccounts package? I found this fork available: https://github.com/abhima9yu/meteor-useraccounts/commit/74a4e48ef11d8b78bffa4d8e6f8a669a39d465a1

Do you think it would work just cloning it locally?

**Comment by softwarerero** [comment]
Yes, https://github.com/meteor-useraccounts/core looks a abandoned, I guess forking it is the best option. If you are able to maintain you can make some users happy.
