### ISSUE TITLE
Some untranslated strings

### ISSUE THREAD

**Issue by fabgua** [softwarerero/meteor-accounts-t9n#199]
I have
Package:
"meteor-accounts-t9n": "^ 2.5.5",
Versions:
softwarerero: accounts-t9n@1.3.11
Many strings are translated correctly, but for some not all the translations are loaded, how is this possible?

![image](https://user-images.githubusercontent.com/84902092/125812573-9685fa79-f34f-4c0b-817c-9f35e983eba7.png)

Thank you very much

**Comment by softwarerero** [comment]
We have four files for Spanish (es, es_formal, es_ES, es_ES_formal) but none of them contains a translation for 'Send email again'. This package exists since 2014 and depends on user contribution which are not always up to date when one of the Meteor accounts packages is updated, so that is how it is possible. 

If you know how to do a [PR](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request) in github you can contribute and add this missing translation and others if you find them. If not let me know and can do. Luckily I speak Spanish but I can do this only for languages I understand.

**Comment by fabgua** [comment]
I think the translations are present in the language files.
But not all translations are displayed, and I don't know why

**Comment by softwarerero** [comment]
Are the two marked translations all you need? I can translate them for you but please let me know all translations you need to do it all at once.

**Comment by fabgua** [comment]
Ok, i found the error
if possible I would like these

  de.coffee  
  #---- without nesting or not loaded
  "Already verified": "Bereits bestätigt"
  "At least 1 digit, 1 lowercase and 1 uppercase": "Mindestens eine Zahl, ein Klein- und ein Großbuchstabe"
  "Invalid email": "Ungültige Emailadresse"
  "Maximum allowed length: 6": "Maximallänge: 6"
  "Minimum required length: 6": "Mindestlänge: 6"
  #---- accounts-password
  "Already verified": "Bereits bestätigt"
  "Please verify your email first. Check the email and follow the link!": "Bitte bestätigen Sie als erstes Ihre Email-Adresse. Prüfen Sie Ihre Emails und folgen Sie dem Link!"

  es.coffee  
  #---- without nesting or not loaded
  "A new email has been sent to you. If the email doesn't show up in your inbox, be sure to check your spam folder.": "Se le ha enviado un nuevo correo electrónico. Si el correo electrónico no aparece en su bandeja de entrada, asegúrese de revisar su carpeta de correo no deseado."
  "Already verified": "Ya verificado"
  "At least 1 digit, 1 lowercase and 1 uppercase": "Al menos 1 dígito, 1 minúscula y 1 mayúscula"
  "Invalid email": "Email inválido"
  "Required Field": "Campo requerido"
  "Send again": "Enviar de nuevo"
  "Send email again": "Enviar correo de nuevo"
  "Send the verification email again": "Enviar el correo electrónico de verificación de nuevo"
  "Verification email lost?": "¿Perdió el correo electrónico de verificación?"
  "Maximum allowed length: 6": "Longitud máxima permitida: 6"
  "Minimum required length: 6": "Longitud mínima requerida: 6"
  
  pt.coffee  
  #---- without nesting or not loaded
  "Send the verification email again" : "Reenviar e-mail de verificação",
  "Send email again" : "Reenviar e-mail"
  "A new email has been sent to you. If the email doesn't show up in your inbox, be sure to check your spam folder.": "Se le ha enviado un nuevo correo electrónico. Si el correo electrónico no aparece en su bandeja de entrada, asegúrese de revisar su carpeta de correo no deseado."
  "Already verified": "Ya verificado"
  "At least 1 digit, 1 lowercase and 1 uppercase": "Al menos 1 dígito, 1 minúscula y 1 mayúscula"
  "Invalid email": "Email inválido"
  "Required Field": "Campo requerido"
  "Send again": "Enviar de nuevo"
  "Send email again": "Enviar correo de nuevo"
  "Send the verification email again": "Enviar el correo electrónico de verificación de nuevo"
  "Verification email lost?": "¿Perdió el correo electrónico de verificación?"
  "Maximum allowed length: 6": "Longitud máxima permitida: 6"
  "Minimum required length: 6": "Longitud mínima requerida: 6"
  
  it.coffee
  #---- accounts-base
  "Already verified": "Gi\à verificato"
  #---- accounts-password
  "Please verify your email first. Check the email and follow the link!": "Per favore, verifica prima la tua email. Controlla la tua email e segui il collegamento che ti è stato inviato."

  fr.coffee
  #---- without nesting or not loaded
  "A new email has been sent to you. If the email doesn't show up in your inbox, be sure to check your spam folder.": "Un nouvel e-mail vous a été envoyé. Si l'e-mail n'apparaît pas dans votre boîte de réception, vérifiez bien votre dossier spam."
  "Already verified": "Déjà vérifié"
  "At least 1 digit, 1 lowercase and 1 uppercase": "Au moins 1 chiffre, 1 minuscule et 1 majuscule"
  "Invalid email": "Email invalide"
  "Required Field": "Champs requis"

**Comment by softwarerero** [comment]
Thanks for the list. There are a few keys you want to introduce on the top level which already exist for `accounts-password`. Before introducing redundant keys which will increase the bandwidth for all users I would like to double-check where those keys come from. Can you point to the places they are used in one of the meteor accounts packages?

The keys I'm curious about are:
- A new email has been sent to you. If the email doesn't show up in your inbox, be sure to check your spam folder.
- Already verified
- At least 1 digit, 1 lowercase and 1 uppercase
- Invalid email

**Comment by fabgua** [comment]
I have seen it, but they are not translated if they are nested.
Those strings in some language files are nested, in others they are not
It is necessary to place them non-nested

![test](https://user-images.githubusercontent.com/84902092/125943075-ff47884a-810a-4cd6-a77f-0961e46b7d39.png)

**Comment by softwarerero** [comment]
2.6.0 is out.

**Comment by fabgua** [comment]
I have updated but it doesn't work

**Comment by fabgua** [comment]
I am not sure about the problem, can you try these files?

[lang.zip](https://github.com/softwarerero/meteor-accounts-t9n/files/6840189/lang.zip)

**Comment by softwarerero** [comment]
I do not understand what your problem is. Here is an example using some of you new translations: https://github.com/softwarerero/t9n-2.6test
