### ISSUE TITLE
Incorrect locale information provided

### ISSUE THREAD

**Issue by ddaydd** [softwarerero/meteor-accounts-t9n#200]
Hello,

if i set
`T9n.setLanguage('zh-CN')`
i get
`T9n.getLanguage()` // zh_CN
and
`new Intl.DateTimeFormat("zh_CN").format(new Date())`
return error  Incorrect locale information provided

but this works
`new Intl.DateTimeFormat("zh-CN").format(new Date())`

how to do?

Thanks :)

**Comment by softwarerero** [comment]
Unfortunately the locale strings are different, so you need to set them differently as in your example. t9n is not using DateTimeFormat, so there will be no conflict, it's just not nice.
