### ISSUE TITLE
Is this compatible post meteor 2.2?

### ISSUE THREAD

**Issue by vparpoil** [softwarerero/meteor-accounts-t9n#201]
Hi @softwarerero !
I have trouble make the npm version work with Meteor 2.7.3. I used to have a working setup on Meteor <= 2.2 with the atmosphere package.

Here are the steps I followed on a bare new app to test reactivity: 
```bash
meteor npm install --save meteor-accounts-t9n
```

```js
import Tracker from "meteor/tracker";

T9n = (require('meteor-accounts-t9n')).T9n;
T9n.setTracker(Tracker);
const T9N_en = require('meteor-accounts-t9n/build/en');
T9n.map('en', T9N_en);
const T9N_fr = require('meteor-accounts-t9n/build/fr');
T9n.map('fr', T9N_fr);
T9n.setLanguage("fr")
```

And still, language is displayed in english in `{{>atForm}}` and no reactivity at all when triggering `T9n.setLanguage("fr")` (or `en`)

I guess I am missing something, any advice would be very usefull, thank you very much!

**Comment by Grubba27** [comment]
Hey can you share a snippet of your blaze code as well? 
It could be a repo with this issue of yours. We may be able to track down what is wrong and fix it :)

**Comment by softwarerero** [comment]
I just create a project with 2.7.3 and to my relieve tracker seems to still do its job. 

main.html:

```
<head>
  <title>t9n-meteor-2.7.3</title>
</head>

<body>
  <h1>Welcome to meteor-t9n!</h1>

  {{> hello}}
</body>

<template name="hello">
  <button>Click me to change the language</button>
  <p>You have choosen {{t 't9Name'}}</p>
</template>
```

main.js:

```
import { Template } from 'meteor/templating'
import { ReactiveVar } from 'meteor/reactive-var'
import Tracker from "meteor/tracker"

import './main.html'
import { T9n } from 'meteor-accounts-t9n'

T9n = (require('meteor-accounts-t9n')).T9n
Template.registerHelper('t', label => T9n.get(label));

T9n.setTracker(Tracker)
const T9N_en = require('meteor-accounts-t9n/build/en')

const T9N_fr = require('meteor-accounts-t9n/build/fr')
T9n.map('fr', T9N_fr)

Template.hello.events({
  'click button'(event, instance) {
    const newLang = T9n.getLanguage() === 'fr' ? 'en' : 'fr'
    T9n.setLanguage(newLang)
  },
})
```

**Comment by vparpoil** [comment]
My blaze code is as simple as :
```html
<body>
  <h1>Welcome to Meteor!</h1>

  {{> hello}}
  {{> info}}
    {{> atForm}}
</body>
```
I was expecting the atForm templates to change language

**Comment by vparpoil** [comment]
Re-opening, because efetively I tested your code with Meteor 2.2 and the atmosphere package and it worked well.

I only added `{{> atForm}}` to the code presented above and it's clear that translations are not happening in the accounts-templates, see code and printscreen bellow


```html
<head>
    <title>t9n-meteor-2.7.3</title>
</head>

<body>
<h1>Welcome to meteor-t9n!</h1>

{{> hello}}
</body>

<template name="hello">
    <button>Click me to change the language</button>
    <p>You have choosen {{t 't9Name'}}</p>
    {{> atForm}}
</template>
``` 

```js
import { Template } from 'meteor/templating'
import { ReactiveVar } from 'meteor/reactive-var'
import Tracker from "meteor/tracker"

import './main.html'
import { T9n } from 'meteor-accounts-t9n'

T9n = (require('meteor-accounts-t9n')).T9n
Template.registerHelper('t', label => T9n.get(label));

T9n.setTracker(Tracker)
const T9N_en = require('meteor-accounts-t9n/build/en')

const T9N_fr = require('meteor-accounts-t9n/build/fr')
T9n.map('fr', T9N_fr)

Template.hello.events({
    'click button'(event, instance) {
        const newLang = T9n.getLanguage() === 'fr' ? 'en' : 'fr'
        T9n.setLanguage(newLang)
    },
})
```
<img width="407" alt="Capture d’écran 2022-10-22 à 10 54 14" src="https://user-images.githubusercontent.com/1492912/197330569-0ff5f4d7-b83e-4f07-831a-d883aa0c205c.png">

**Comment by vparpoil** [comment]
Ok, I think I get it this time :
the last useraccounts-core which is a meteor-compat package[ exports T9n as a global variable](https://github.com/meteor-compat/useraccounts-core/blob/25235ebeec5273b934d6214043a36171b142ad5f/package.js#L83) 

So to make it work with accounts-templates, one need to remove direct references to this package, the two folllowing lines must be removed : 
```
import { T9n } from 'meteor-accounts-t9n'
T9n = (require('meteor-accounts-t9n')).T9n
```

Closing the issue, thank you for your time 👍
