### ISSUE TITLE
Return map of all supported language codes and translations

### ISSUE THREAD

**Issue by softwarerero** [softwarerero/meteor-accounts-t9n#73]
Create a function T9n.getLanguages() that returns a map of language codes and translations:
```
[
  {name: "English", code: "en"},
  {name: "Italiano", code: "it"},
  {name: "Español", code: "es"},
]
```

**Comment by carrot93** [comment]
T9n.getLanguages() return a language list, but I found some problems:
1. packages.js defined: DEFAULT_LANGUAGES, it's no 'hu' or else.
2. T9n.getLanguages() list that the zh-cn should be zh_cn, but I must use T9n.setLanguage('zh-cn') to change Chinese Language. For example: T9n.setLanguage('hu') /T9n.setLanguage('zh_cn') is no effect on client, but still can use T9n.setLanguage('en')/('de')/('vi')/('zh-cn')/....
3. I m confused for that if I want to make Login Interface with International supported.

**Comment by softwarerero** [comment]
It sounds like your working with an older version of t9n. Can you please check that your version of package.js is 1.1.0.

**Comment by carrot93** [comment]
Yes，it's softwarerero:accounts-t9n 1.1.0. And I confused zh_tw is ok, zh_cn can't , but zh-cn is correct in there. And I can't find bug about section of "@registerMap" or "@replaceParams".

**Comment by softwarerero** [comment]
I see what happened: 1.1.0 was released on 3rd of April and Luca fixed this on the 15th of April. I did a new release 1.1.1 now, please give it at try.

**Comment by softwarerero** [comment]
With version 1.2.0 comes `T9n.getLanguageInfo()` which returns a structure like above. 

Off course I could only provide translations for some languages, so all contributors are invited to a string for `t9Name`.
