### ISSUE TITLE
zh-tw and zh_tw

### ISSUE THREAD

**Issue by txs** [softwarerero/meteor-accounts-t9n#78]
When I put T9n.getLanguages() in my console.. it says that the zh-tw is zh_tw... different than the doc.
What's the problem?

T9n.getLanguages()
["ar", "cs", "da", "de", "el", "en", "es", "es_ES", "fa", "fr", "he", "it", "nl", "no_NB", "pl", "pt", "ru", "sl", "sv", "uk", "vi", "zh-cn", "zh_tw"]

Sincerely,

txs

**Comment by softwarerero** [comment]
Thanks for the hint. This should be fixed in the next release.

**Comment by txs** [comment]
Got it fixed,  not a big deal
