### ISSUE TITLE
Using tap-i18n

### ISSUE THREAD

**Issue by mquandalle** [softwarerero/meteor-accounts-t9n#79]
Hello,

I'm I using https://github.com/TAPevents/tap-i18n to internationalize my meteor application and I would like third parties packages to integrate with the existing system as much as possible. Would it be possible to use this package to handle the translation logic? With that for instance, we won't have to add all translations to the meteor bundle — and could instead request each translation file on demand.

Or maybe this architectural change is too big and  I should start an alternative package to implement it?

**Comment by softwarerero** [comment]
Hello, I do not thing I understand what you want to do. I had a short look at tap-i18n. It seems they have a much broader scope. T9n only focuses on the translation part, not on full internationalization. It should be easy to integrate t9n into any full i18n solution, just use the translations and ignore the logic part. Probably you can give me some more details what you have in mind.

**Comment by softwarerero** [comment]
Would be able to give some more information about your use case?

**Comment by bySabi** [comment]
I think  `meteor-accounts-t9n` must split on multiple meteor package like do  https://github.com/rzymek/meteor-moment
Then add only language need per project not all translation files.
Like:
 `meteor add softwarerero:accounts-t9n-es` for Spanish translation.

This is a must have.

**Comment by softwarerero** [comment]
Is this a a duplicate with https://github.com/softwarerero/meteor-accounts-t9n/issues/83?

**Comment by softwarerero** [comment]
With Version 1.1.0 you can send only specific translations to the client.
