### ISSUE TITLE
Split `meteor-accounts-t9n` per translation packages. 

### ISSUE THREAD

**Issue by bySabi** [softwarerero/meteor-accounts-t9n#83]
I think `meteor-accounts-t9n` must split on multiple meteor package like do [rzymek:meteor-moment](https://github.com/rzymek/meteor-moment)

Then add only needed language per project not all translation files.
Like Ex:

`meteor add softwarerero:accounts-t9n-es` for Spanish translation.

This is a must have.

**Comment by softwarerero** [comment]
Why? What is your use case?

**Comment by bySabi** [comment]
Maybe cause `meteor-accounts-t9n`is too bloated right now.

I did it some test like in production workflow:
1- Convert all coffescript files to JS
2- Minimized JS files with UglyfyJS
3- Concat all translation files on one `all-lang.min.js`
4- Concat default translation `en.js`and for example `es_ES.js`
5- Finally compress with gzip.
 
this are the numbers:

`t9n.js.gz` + `all-lang.js.gz` =  `24KB`
`t9n.js.gz` + `ES-lang.js.gz` =  `2KB`

Right now I have `22KB` of unneeded code on the client side.

**Comment by softwarerero** [comment]
Understood. It's on the todo list then. Pull requests are welcome.

**Comment by softwarerero** [comment]
This should be posible with version 1.1.0.
