### ISSUE TITLE
Confuse doc

### ISSUE THREAD

**Issue by engenheiro** [softwarerero/meteor-accounts-t9n#89]
Hello, the docs need more information about how we can start to use your package. I tried put the "T9n.setLanguage("es")" in a JS client also in server and dont works.

**Comment by softwarerero** [comment]
I am sorry to hear that. Can you tell what you did, what you expected and what did not work? Did you get an error?

**Comment by engenheiro** [comment]
I dont have a error. The package looks great but I dont know how start. Please, you can describe in the docs, step by step how to works?

**Comment by softwarerero** [comment]
Sorry, I do not really understand what information you need.
