### ISSUE TITLE
problem with T9n.get(code) no change when switch lang?

### ISSUE THREAD

**Issue by yuomtheara** [softwarerero/meteor-accounts-t9n#94]
I use `T9n` and `lang`.
I set label of `simple-schema` by `T9n.get(code)`, but the label don't change when switch to other lang
```
T9n.map('en', {
    "sayHello": 'Hi @{name}'
});

/**
 * Kh
 */
T9n.map('kh', {
    "sayHello": '​សួស្តី @{name}'
});

...
module: {
        type: String,
        label: T9n.get("sayHello", true, {name: "Theara"})
    },
```

**Comment by softwarerero** [comment]
I do not see where you set the language. Somewhere you should issue ```T9n.setLanguage("es")``` before you call ```get```.

**Comment by softwarerero** [comment]
Is this still open?

**Comment by yuomtheara** [comment]
Excuse me, work fine.
