### ISSUE TITLE
request add params direct on {{t9n code param1="thera" param2="..."}}?

### ISSUE THREAD

**Issue by yuomtheara** [softwarerero/meteor-accounts-t9n#95]
request add params direct on `{{t9n code}}` like:
```
{{t9n code name="Theara" param2="..."}}
```

**Comment by softwarerero** [comment]
Yoy can try {{t9n code [name: "Theara", param2:"..."] }}, this should work already.

**Comment by yuomtheara** [comment]
I try, but not work.

**Comment by softwarerero** [comment]
Try this: ```{{t9n 'code' name='Theara' param2='...'}}``` and let me know. I made a little fix.

**Comment by yuomtheara** [comment]
still not work  how: `Hi @{name}`

**Comment by softwarerero** [comment]
When I register ```T9n.map 'de', 'code': 'Hi @{name}'``` and then call ```{{t9n 'code' name='Theara'}}``` in the template I get ```Hi Theara```. Let's find out what is different. Do you work with my latest checkin?

**Comment by yuomtheara** [comment]
I try `run meteor update`, but can't see new version (softwarerero:accounts-t9n@1.0.8)

**Comment by yuomtheara** [comment]
after i check source code in `.meteor` folder, 
```
Meteor.startup(function() {
  if (Meteor.isClient) {
    return UI.registerHelper('t9n', function(x, params) {
      return T9n.get(x, true, params);
    });
  }
});
```

**Comment by softwarerero** [comment]
Right, it is not in 1.0.8. Would you be able to test with the current trunk? If not I will release 1.0.9.

**Comment by yuomtheara** [comment]
wait for your update.

**Comment by softwarerero** [comment]
done

**Comment by yuomtheara** [comment]
Very thanks, please update docs.

**Comment by yuomtheara** [comment]
wow, I run `meteor update` but don't get the new version.

**Comment by softwarerero** [comment]
1.0.9 is out
