### ISSUE TITLE
don't understand "Translations are currently available for..." on docs?

### ISSUE THREAD

**Issue by yuomtheara** [softwarerero/meteor-accounts-t9n#96]
I don't understand `Translations are currently available for...` on docs?
It mean that this package can translation by itself or still config file.
```
T9n.map('en', {
    "sayHello": 'Hi @{name}'
});

/**
* Kh
*/
T9n.map('kh', {
    "sayHello": '​សួស្តី @{name}'
});
```

**Comment by softwarerero** [comment]
You get translations for accounts-base, accounts-passwords, accounts-entry, accounts-templates-core and billing that come with the module. You can add whatever translations you want or need for you application. I usually have a folder ```lib/t9n``` where I put my translations, e.g.:

```
en =
  name: "Name"

T9n.map "en", en
```
That way I can use the translations on the client and on the server.

**Comment by yuomtheara** [comment]
Could I request you for `Khmer` of Cambodia support? 
Or how to do this?

**Comment by softwarerero** [comment]
Mh, I do not speak Khmer, but you can easily grab any translation file you find in the folder t9n and translate it yourself. Just send a pull request of your file and I do the rest.

**Comment by yuomtheara** [comment]
Very thank I will try, because i am not good to use git.

**Comment by softwarerero** [comment]
If you do not know how to send a pull request just send me an email with your file.

**Comment by yuomtheara** [comment]
Thanks again, I will send you.
please give me your email.

**Comment by softwarerero** [comment]
https://github.com/softwarerero

**Comment by yuomtheara** [comment]
now i send you the Khmer already.
